version: "3"
services:
    mongodb:
        image: mongo:4.2
        container_name: mongodb
        network_mode: host
        restart: always
        # command: mongod --dbpath /data/db --port 27017
        volumes: [./data:/data/db]
        ports:
            - "27017:27017"
        
    backend:
        image: backend-flask
        depends_on: [mongodb]
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        container_name: "backend-app"
        links:
            - 'mongodb:database'
        volumes:
            - ./backend:/app # for watching files
        ports:
            - "8081:8081" # if changed, please change port in `frontend/proxy.conf.dev.json
    frontend:
        image: frontend-angular
        depends_on: [backend]
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        container_name: "frontend-app"
        volumes:
            - ./frontend/src:/app/src # for watching files
        ports:
            - "4200:4200"

    