version: "3"
services:
    database:
        image: mongo
        container_name: mongo
        restart: unless-stopped
        command: mongod --dbpath /data/db --port 27017
        volumes: 
            - ./data:/data/db
        networks:
            - backend_net
       
    backend:
        image: backend-flask
        depends_on:
            - database
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: "backend-app"
        
        links:
            - database
        volumes:
            - ./backend:/app # for watching files
        ports:
            - "8081:8081" # if changed, please change port in `frontend/proxy.conf.dev.json
        networks:                   
            - frontend_net
            - backend_net

    frontend:
        image: frontend-angular
        depends_on: 
            - backend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: always
        container_name: "frontend-app"
        volumes:
            - ./frontend/src:/app/src # for watching files
        ports:
            - "4200:4200"
        
        networks:
            - frontend_net

networks:
    frontend_net:
        driver: bridge
    backend_net:
        driver: bridge

    